### ISSUE TITLE
Link to Pebble heart badge image broken

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-pebbletime#15]
**Summary:** 

On http://onebusaway.org/, the link to the Pebble badge image is currently broken:

![image](https://cloud.githubusercontent.com/assets/928045/23307920/56eedfd0-fa77-11e6-9da0-455382873fd7.png)

Current link for the image is http://pblweb.com/badge/58321a598c7fff9ce1000137/black/small/.

@kmwoley Do you know what the new link should be?

**Comment by barbeau** [comment]
Looking more, we were using a 3rd party service to dynamically generate the icon so it contained the number of "hearts" (i.e., "likes"), and this service appears inactive now.  So we can just replace the icon with a static badge icon.  It should be 44 pixels tall to match the height of the other badges (and variable width).

The original issue for creating the badge was at https://github.com/OneBusAway/onebusaway-pebbletime/issues/8.

**Comment by barbeau** [comment]
Alright, I've updated the icon using the below, but the height attribute isn’t working right.  Fixing it requires configuration under “Appearance->Widgets”, and then “Home Widget 1” card in the right section of page.  If you click on “Text: Mobile…” it opens up the box to edit.  Will try again later...

![pebble_2x](https://cloud.githubusercontent.com/assets/928045/24364363/97193b06-12e0-11e7-93e5-8f618e572665.png)

**Comment by barbeau** [comment]
Fixed.  From Neveen at HART:

>It worked when using width=”121”, I measured it and 44.2 px in height came out to 121 px width. 

![image](https://cloud.githubusercontent.com/assets/928045/24378403/cc6cf2a4-1310-11e7-9b41-47ff7d43f9c2.png)

**Comment by kmwoley** [comment]
Thanks for taking care of this - I had somehow missed the notification from the original issue until today.

**Comment by barbeau** [comment]
No problem! Let me know if you figure out the dynamic image and we can swap that one back in.
