### ISSUE TITLE
Please Link Pebble Dev Account to a Rebble Account

### ISSUE THREAD

**Issue by CameronDevine** [OneBusAway/onebusaway-pebbletime#16]
To allow the continued use and updates of One Bus Away on Pebble Devices, please make a Rebble account and link the Pebble Developer account for this Pebble app.

You can read more about Rebble here,
http://rebble.io/2018/06/13/get-ready-to-rebble.html

**Comment by kmwoley** [comment]
Done and done. Thanks for doing proactive outreach and good luck with the
switch over!
