### ISSUE TITLE
Departures and arrivals are sometimes interchanged in text

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-pebbletime#5]
In OBA, records from the `arrivals-and-departures-from-stop` API can represent either arrivals at that stop, or departures at that stop.  A common bug that's existed in most OBA UIs at some point is showing all of these records as arrivals when the ETA is positive, and then a departure when the ETA is negative (i.e., the bus is coming, and it just left).

For example, here are two screenshots, with positive ETA on left, and negative ETA on right:

![image](https://cloud.githubusercontent.com/assets/928045/20850296/6726d8b4-b8a8-11e6-8247-a34ae5757b31.png)

Reality is a little more nuanced for these the below conditions:

1. Transit Centers - When looking at transit centers, buses for the same route are (typically) arriving with one headsign, waiting a short time (layover), and then departing with a new headsign.  You'll see records for both these arrivals and departures from `arrivals-and-departures-from-stop` at the transit center.
1. Layovers - Sometimes a route will have a short layover in the middle of the route - in that case, you'll see records for the arrival to this "break" stop, and the departure from this "break" stop in `arrivals-and-departures-from-stop` at this stop.
1. Loop routes - For routes in a loop, one stop in the loop will be designated as the beginning and end stop in the data.  In this case, you'll see records for the arrival to this loop stop and departure from this loop stop.

When times are always shown as "arrives in" for positive ETAs, in the above cases this is incorrect - these records should say "departs in".  

Additionally, when times are always shown as "departed at ..." for negative ETAs, in the normal case this is also incorrect - it should actually say "arrived at ...".

A simple way to implement this in code is the following (pulled from Android):

~~~
if (info.getStopSequence() != 0) {
    // Show arrival time
    scheduled = info.getScheduledArrivalTime();
    predicted = info.getPredictedArrivalTime();
    mIsArrival = true;
} else {
    // Show departure time
   scheduled = info.getScheduledDepartureTime();
   predicted = info.getPredictedDepartureTime();
   mIsArrival = false;
}
~~~

If `mArrival` is true, then the text would be "arriving in..." for positive ETAs, and "arrived at" for negative ETAs.

If `mArrival` is false, then the text would be "departing in..." for positive ETAs, and "departed at" for negative ETAs.

And after this code block `scheduled` and `predicted` would always contain the time used to calculate the ETA properly for the arrival or departure.

`getStopSequence() == 0` is testing if the stop is the first stop in the trip.

Here's how this looks on Android:

![image](https://cloud.githubusercontent.com/assets/928045/14091291/66390012-f50d-11e5-9bdc-1185d9e10acf.png)

More discussion at https://github.com/OneBusAway/onebusaway-iphone/issues/617#issuecomment-242850914.

**Comment by kmwoley** [comment]
Great - thanks for the details here. This should be a pretty easy fix.
