### ISSUE TITLE
Change red/blue/green shades for early/late/on time arrivals

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-pebbletime#6]
In the OBA Android v2 UI redesign, I changed the shade of red, blue, and green to be a little less harsh than the pure RGB, based on the [triadic colors](http://www.homedit.com/triadic-color-scheme/) from the green shade we're using for the theme color for Action Bar, menues, etc.  

Here's what we're currently using in OBA Android:
* Red (late) - #af504c
* Blue (early) - #504caf
* Green (on time) - #4CAF50
* Gray (scheduled - no real-time info) - #777

![image](https://cloud.githubusercontent.com/assets/928045/20850923/979e43b2-b8ab-11e6-8008-18d398037048.png)

@kmwoley I'd suggest taking a look at these on an actual Pebble device and see if these colors are an improvement - if not, feel free to stick with what you're currently using.

**Comment by kmwoley** [comment]
Unfortunately, there's not a lot of options when it comes to what [colors you can display on the pebble](https://developer.pebble.com/docs/c/Graphics/Graphics_Types/Color_Definitions/). The colors I chose were the closest matches I could find to what I saw on OBA Android.

Also, the colors appear a lot more harsh in the emulator than they do no the actual device's e-ink display. I should take a picture of the actual device so you can see sometime. :)

**Comment by barbeau** [comment]
Works for me!
