### ISSUE TITLE
Image for badge on onebusaway.org

### ISSUE THREAD

**Issue by barbeau** [OneBusAway/onebusaway-pebbletime#8]
**Summary:** 

I'd like to add a badge for the OBA Pebble app to onebusaway.org:
http://onebusaway.org/

These badges are all 44 pixels tall, and variable width depending on what's standard for each platform.

@kmwoley Could you please attach (drag/drop) a badge for OBA Pebble in this issue?  I'll then take care of adding it to oba.org.

Also, please let me know exactly what URL the hyperlink should point to.  Thanks!

**Comment by kmwoley** [comment]
What do you think about using one of the following badges?

They are taller than requested, but are pretty common for Pebble apps (they dynamically update showing the app-store 'heart' count).

I prefer the white one in the middle, but I think picking whatever works well for the OBA page would work for me.

![Orange Small](http://pblweb.com/badge/58321a598c7fff9ce1000137/orange/small)
![White Small](http://pblweb.com/badge/58321a598c7fff9ce1000137/white/small)
![Black Small](http://pblweb.com/badge/58321a598c7fff9ce1000137/black/small)

They should hyperlink to https://apps.getpebble.com/applications/58321a598c7fff9ce1000137

**Comment by kmwoley** [comment]
FYI - you can request different sizes via the url as well (small, medium, large).
I've found that if you select the medium size and then resize it via HTML you end up with a better image.

Example:
<img src="http://pblweb.com/badge/58321a598c7fff9ce1000137/white/medium/" height="44">

**Comment by barbeau** [comment]
@kmwoley Thanks, those should work!  I think the black or orange background would fit best with the other badges on oba.org.  Let me dig in a bit...

**Comment by barbeau** [comment]
Done!  See http://onebusaway.org/ for the finished product. :)

![image](https://cloud.githubusercontent.com/assets/928045/21375142/935a2ecc-c6f9-11e6-8a76-0eb02a0b8e6b.png)
