### ISSUE TITLE
Use Regions API instead of hard-coding regions list

### ISSUE THREAD

**Issue by kmwoley** [OneBusAway/onebusaway-pebbletime#9]
**Summary:** 

http://regions.onebusaway.org/regions-v3.json
http://regions.onebusaway.org/regions-v3.xml

It's a centralized API to dynamically pull back a list of supported OBA regions, including their geographic boundaries and server APIs. Documentation for this is hosted separately from the central OBA docs (we need to fix this), so some devs miss it.

More info at https://github.com/OneBusAway/onebusaway-application-modules/wiki/API-Webapp-Configuration-Guide#new-3rd-party-mobile-apps---api-key-generation-and-sharing-process.

**Comment by barbeau** [comment]
Here's the AsyncTask that Android runs that hits the Regions API and then provides a callback to the app - https://github.com/OneBusAway/onebusaway-android/blob/master/onebusaway-android/src/main/java/org/onebusaway/android/region/ObaRegionsTask.java.

Other utilities are in the same `/region/` package.

**Comment by barbeau** [comment]
For OBA Alexa, I ported the OBA Android client code to regular Java and stuck it in a [onebusaway-client-library](https://github.com/OneBusAway/onebusaway-client-library) to make it easier to write clients in the future.

Not sure if that's any more useful than the Android Java code on Pebble, but here are the library utilities:
https://github.com/OneBusAway/onebusaway-client-library/blob/master/src/main/java/org/onebusaway/io/client/util/RegionUtils.java

...and request library object:
https://github.com/OneBusAway/onebusaway-client-library/blob/master/src/main/java/org/onebusaway/io/client/request/ObaRegionsRequest.java

Main class encapsulating the calls to the library in Alexa:
https://github.com/OneBusAway/onebusaway-alexa/blob/master/src/main/java/org/onebusaway/alexa/lib/ObaUserClient.java

Here's this encapsulating class being used in Alexa:
https://github.com/OneBusAway/onebusaway-alexa/blob/master/src/main/java/org/onebusaway/alexa/AnonSpeechlet.java#L120
